ENV: prod
url: https://www.nisix.net
frontendUrl: https://www.nisix.net
port: 3000

database:
  url: ${DATABASE_URL}
  synchronize: false
  logging: false

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiresIn: 3600 # 1 hour
